### ISSUE TITLE
Callback context

### ISSUE THREAD

**Issue by mistic100** [malko/D.js#17]
Hello

though not part of the promises/A+ spec I think it would be a nice addition to be able to specify the execution context of the callbacks.

For example with a bind method which store the context :
```js
  var defer = D().bind(this);
```

**Comment by malko** [comment]
As stated in your comment this is not in the A+ spec and i don't want to add this to D.js
You always can bind a context to your callback method before passing it to then or even better use an arrow function with ES2015.

Thanks anyway for your interest in D.js

**Comment by mistic100** [comment]
As you already added methods not in the spec you could have added this one.

Yeah I'm binding manually instead, same result and better granumlarity actually :-) (and I don't want to use ES6 transpilers).
