### ISSUE TITLE
Is D.js on a CDN anywhere? 

### ISSUE THREAD

**Issue by Parth** [malko/D.js#20]
Googling for D.js is particularly difficult :laughing:

**Comment by malko** [comment]
No, i've never felt the need for this but if you know a free cdn you want to use we can do it.

**Comment by Parth** [comment]
[I think this would be a really easy way for you to just use the files on git as a cdn](https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github)

**Comment by malko** [comment]
Updated readme with the rawgit link
