### ISSUE TITLE
D.js is an invalid AMD module name

### ISSUE THREAD

**Issue by speich** [malko/D.js#21]
The AMD module definition states that 

> Module identifiers may not have file-name extensions like ".js".

Exporting "D.js" as the module id prevents AMD loaders from loading this dependency properly: https://github.com/malko/D.js/blob/5217f4c04a047b3695ab51751c0bf8666317aa10/lib/D.js#L434

**Comment by malko** [comment]
Not sure how to fix this properly without breaking people using it that way if any. I can make a minor release but It would be without real change in it so.... What do you think about it @speich ?

**Comment by speich** [comment]
I don't think you can break all that much, since it's currently not possible to load the module with AMD anyway, at least for loaders that stick to the rules. For example, the module name 'D.js', is interpreted by the dojotoolkit loader simply as a generic JavaScript and not as a module
@see https://dojotoolkit.org/reference-guide/1.10/loader/amd.html#generic-script-injection

Don't now about other loaders though. So I leave it up to you if you want to change the name to 'D',  but I think it's better to correct (and maybe break something) sooner than later...
